### ISSUE TITLE
Using sqlite3 in datasources.json

### ISSUE THREAD

**Issue by shalkam** [strongloop/loopback-connector-sqlite3#16]
Hi,
Is it possible to use this connector inside datasources.json or is it strictly for the js file?

**Comment by 0candy** [comment]
You should be able to use this connector in datasources.json. Are you seeing errors?

**Comment by superkhau** [comment]
@shalkam Yes, you can.

For future referene, please post questions at on our [Google Groups forum](https://groups.google.com/forum/#!forum/loopbackjs) or try asking using live chat on our [Gitter](https://gitter.im/strongloop/loopback). We reserve GitHub issues for features and bug reports only. See https://github.com/strongloop/loopback/wiki/Questions for more details.
