### ISSUE TITLE
this repo is private, but it shouldn't be if its published to npmjs.org, I think

### ISSUE THREAD

**Issue by sam-github** [strongloop/loopback-connector-sqlite3#6]

**Comment by raymondfeng** [comment]
I believe it's public now.

**Comment by rmg** [comment]
:+1:

**Comment by sam-github** [comment]
Though that wasn't enough to get the npmjs page, https://www.npmjs.com/package/loopback-connector-sqlite3, to show the link to github. Probably needs republish.
